RailwaySystem/RailwaySystem/Models/PassengerDetails.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RailwaySystem.Models
{
    [Table("PassengerDetails")]
    public class PassengerDetails
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PNR { get; set; }
        
        [Required]
        public int UserID { get; set; }

        [Required]
        public string Name { get; set; }
        public bool Gender { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }

        [Required]
        public string Source { get; set; }

        [Required]
        public string Destination { get; set; }
        public DateTime Departure{ get; set; }
        public int TrainNo { get; set; }
        public int Compartment { get; set; }
        public string SeatCode { get; set; }
        public decimal Price { get; set; }
        public DateTime BookingDate { get; set; }
        
    }
}

RailwaySystem/RailwaySystem/Controllers/TrainDetailsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RailwaySystem.Models;
using RailwaySystem.Repository;
using RailwaySystem.Services;
using System;
using System.IO;
using System.Linq;
using System.Text;

namespace RailwaySystem.Controllers
{
    public class TrainDetailsController : Controller
    {
        private IHomeServices service;
        public TrainDetailsController(IHomeServices _service)
        {
            this.service = _service;
        }
        //-----
        FServices fServices = new FServices();
        //-----
        public void SaveSession()
        {
            if (HttpContext.Session.GetString("name") != null)
            {
                ViewBag.name = HttpContext.Session.GetString("name");
            }
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewBag.username = HttpContext.Session.GetString("username");
            }
            if (HttpContext.Session.GetString("role") != null)
            {
                ViewBag.role = HttpContext.Session.GetString("role");
            }
            if (HttpContext.Session.GetString("userid") != null)
            {
                ViewBag.userid = HttpContext.Session.GetString("userid");
            }
            //-----
            StreamReader sr = new StreamReader("wwwroot/Visitor.txt");
            int cnt = 0;
            string cnt_ = sr.ReadToEnd().Trim();
            cnt = int.Parse(cnt_);
            sr.Close();
            ViewData["count"] = cnt;
            if (HttpContext.Session.GetString("visitor") == null)
            {
                HttpContext.Session.SetString("visitor", cnt_);
                cnt++;
                StreamWriter sw = new StreamWriter("wwwroot/Visitor.txt");
                sw.Write(cnt);
                sw.Flush();
                sw.Close();
                ViewData["count"] = cnt;
            }
            ViewData["Date"] = fServices.NamThangNgay();
        }
        //-----
        public IActionResult ListTrainDetails(string varLocal)
        {
            SaveSession();
            if (!(ViewBag.role == "True" || ViewBag.username == "ADMIN"))
            {
                return RedirectToAction("Login", "LoginDetails");
            }
            var model = service.GetTrainDetails();
            if (varLocal != null)
            {
                model = model.FindAll(u => u.TrainName.Contains(varLocal));
            }
            return View(model);
        }
        //-----
        [HttpGet]
        public IActionResult Create()
        {
            SaveSession();
            var listarr = service.GetStationArr();
            ViewBag.arr = new SelectList(listarr, "StationCode", "StationName");

            var listdep = service.GetStationDep();
            ViewBag.dep = new SelectList(listdep, "StationCode", "StationName");

            return View();
        }
        [HttpPost]
        public IActionResult Create(TrainDetails varTable)
        {
            SaveSession();
            var listarr = service.GetStationArr();
            ViewBag.arr = new SelectList(listarr, "StationCode", "StationName");

            var listdep = service.GetStationDep();
            ViewBag.dep = new SelectList(listdep, "StationCode", "StationName");

            try
            {
                if ((varTable.Departure - DateTime.Now).TotalHours <= 5)
                {
                    ViewBag.msg = "Departure date must be 5 hours greater than or equal to the current date!";
                    return View();
                }
                var kt = service.GetTrainDetails().Where(k => k.Source.Equals(varTable.Source)
                                && k.Destination.Equals(varTable.Destination)
                                && k.Departure == varTable.Departure);
                if (kt.Count() > 0)
                {
                    ViewBag.msg = "Duplicate data!";
                    return View();
                }
                varTable.Status = true;
                if (varTable.FirstClass + varTable.SecondClass + varTable.ThirdClass + varTable.SleepRoom + varTable.General > 64)
                {
                    ViewBag.msg = "Total number of seats for a car larger than 64!";
                    return View();
                }
                if (varTable.FirstClass + varTable.SecondClass + varTable.ThirdClass + varTable.SleepRoom + varTable.General == 0)
                {
                    ViewBag.msg = "Total number of seats must be greater than 0!";
                    return View();
                }
                if (varTable.Source == varTable.Destination)
                {
                    ViewBag.msg = "Source can't same Destination!";
                    return View();
                }
                if (ModelState.IsValid)
                {
                    service.PostTrainDetails(varTable);

                    var listseatcode = service.GetPriceDetails();
                    var listdisprice = service.GetDisprice().FirstOrDefault(d => (d.Source.Equals(varTable.Source) && d.Destination.Equals(varTable.Destination)) || (d.Source.Equals(varTable.Destination) && d.Destination.Equals(varTable.Source)));

                    SeatDiagram seatDiagram;
                    for (int i = 1; i <= varTable.NoOfCompartment; i++)
                    {
                        foreach (var item in listseatcode)
                        {
                            if (item.SeatCode == "1AC")
                            {
                                for (int j = 1; j <= varTable.FirstClass; j++)
                                {
                                    seatDiagram = new SeatDiagram();
                                    seatDiagram.TrainNo = varTable.TrainNo;
                                    seatDiagram.Compartment = i;
                                    seatDiagram.SeatCode = item.SeatCode;
                                    seatDiagram.SeatOrder = j;
                                    seatDiagram.Price = item.Price + listdisprice.Price;
                                    seatDiagram.UserId = 0;
                                    seatDiagram.Status = true;
                                    service.PostSeatDiagram(seatDiagram);
                                }
                            }
                            if (item.SeatCode == "2AC")
                            {
                                for (int j = 1; j <= varTable.SecondClass; j++)
                                {
                                    seatDiagram = new SeatDiagram();
                                    seatDiagram.TrainNo = varTable.TrainNo;
                                    seatDiagram.Compartment = i;
                                    seatDiagram.SeatCode = item.SeatCode;
                                    seatDiagram.SeatOrder = j;
                                    seatDiagram.Price = item.Price + listdisprice.Price;
                                    seatDiagram.UserId = 0;
                                    seatDiagram.Status = true;
                                    service.PostSeatDiagram(seatDiagram);
                                }
                            }
                            if (item.SeatCode == "3AC")
                            {
                                for (int j = 1; j <= varTable.ThirdClass; j++)
                                {
                                    seatDiagram = new SeatDiagram();
                                    seatDiagram.TrainNo = varTable.TrainNo;
                                    seatDiagram.Compartment = i;
                                    seatDiagram.SeatCode = item.SeatCode;
                                    seatDiagram.SeatOrder = j;
                                    seatDiagram.Price = item.Price + listdisprice.Price;
                                    seatDiagram.UserId = 0;
                                    seatDiagram.Status = true;
                                    service.PostSeatDiagram(seatDiagram);
                                }
                            }
                            if (item.SeatCode == "SLE")
                            {
                                for (int j = 1; j <= varTable.SleepRoom; j++)
                                {
                                    seatDiagram = new SeatDiagram();
                                    seatDiagram.TrainNo = varTable.TrainNo;
                                    seatDiagram.Compartment = i;
                                    seatDiagram.SeatCode = item.SeatCode;
                                    seatDiagram.SeatOrder = j;
                                    seatDiagram.Price = item.Price + listdisprice.Price;
                                    seatDiagram.UserId = 0;
                                    seatDiagram.Status = true;
                                    service.PostSeatDiagram(seatDiagram);
                                }
                            }
                            if (item.SeatCode == "GNE")
                            {
                                for (int j = 1; j <= varTable.General; j++)
                                {
                                    seatDiagram = new SeatDiagram();
                                    seatDiagram.TrainNo = varTable.TrainNo;
                                    seatDiagram.Compartment = i;
                                    seatDiagram.SeatCode = item.SeatCode;
                                    seatDiagram.SeatOrder = j;
                                    seatDiagram.Price = item.Price + listdisprice.Price;
                                    seatDiagram.UserId = 0;
                                    seatDiagram.Status = true;
                                    service.PostSeatDiagram(seatDiagram);
                                }
                            }
                        }

RailwaySystem/RailwaySystem/Views/PassengerDetails/BuyTicket.cshtml
@model IEnumerable<RailwaySystem.Models.SeatDiagram>

@{
    ViewData["Title"] = "BuyTicket";
}

<h3 class="alert-info">Selected seat class list</h3>
<br />
<p>
    <a href="@Url.Action("FindSeat", "PassengerDetails", new {varlocal=ViewBag.trainno,varLocal2 = ViewBag.compartment})">
        <span class="btn btn-success">Back</span>
    </a>
</p>
<h5 style="color:red">@ViewBag.msg</h5>

<h5 style="color:red">Ticket information</h5>
<table width="100%">
    <tr>
        <td width="20%">First and last name:</td>
        <td width="30">@ViewBag.name</td>
        <td width="50%" rowspan="8">
            <hr />
            <h5 style="color:red">CHOOSE PAYING BANK</h5>
            <hr />
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                    Techcombank
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
                <label class="form-check-label" for="flexRadioDefault2">
                    Vietcombank
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
                <label class="form-check-label" for="flexRadioDefault2">
                    Vietinbank
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
                <label class="form-check-label" for="flexRadioDefault2">
                    BIDV
                </label>
            </div>
            @if (ViewBag.msg == null)
            {
                <hr />
                <div>
                    <p><a style="color:blueviolet">Payment content: Buy train tickets></a></p>
                    <p><a style="color:blue">Amount of money:&nbsp;</a><a><span class="btn btn-warning"><strong>@ViewBag.sum&nbsp;VNĐ</strong></span></a></p>
                </div>
                @if (ViewBag.ok == null)
                {
                    <div>
                        <a href="@Url.Action("BuyTicket", "PassengerDetails", new {varlocal=ViewBag.trainno,varLocal2 = ViewBag.compartment,payment=1})">
                            <span class="btn btn-danger">Ticket payment</span>
                        </a>
                    </div>
                }
                @if (ViewBag.ok == "OK")
                {
                    <hr />
                    <div>
                        <p><a style="color:brown">Thank you for using the service. Tickets have been successfully paid. Please select Print Tickets button to get QR Code for ticket control when boarding.</a></p>
                    </div>
                    <div>
                        <a href="@Url.Action("PrintTickets", "PassengerDetails", new {varlocal=ViewBag.userid})">
                            <span class="btn btn-success">Print Tickets</span>
                        </a>
                    </div>
                }
            }
        </td>
    </tr>
    <tr>
        <td>Gender:</td>
        <td>@ViewBag.gender</td>
    </tr>
    <tr>
        <td>Phone:</td>
        <td>@ViewBag.phone</td>
    </tr>
    <tr>
        <td>Address Email:</td>
        <td>@ViewBag.email</td>
    </tr>
    <tr>
        <td>Train:</td>
        <td>@ViewBag.trainname</td>
    </tr>
    <tr>
        <td>Station go:</td>
        <td>@ViewBag.source</td>
    </tr>
    <tr>
        <td>Arrivals:</td>
        <td>@ViewBag.destination</td>
    </tr>
    <tr>
        <td>Departure:</td>
        <td>@ViewBag.departure</td>
    </tr>
</table>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TrainNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Compartment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeatCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeatOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TrainNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Compartment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SeatCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SeatOrder)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            </tr>
        }
        <tr>
            <td colspan="4" align="center"><a class="btn btn-info btn-block" style="color:white"><strong>Total</strong></a></td>
            <td align="left"><a class="btn btn-warning"><strong>@ViewBag.sum&nbsp;VNĐ</strong></a></td>
            <td>
            </td>
            <td>&nbsp;</td>
        </tr>
    </tbody>
</table>

RailwaySystem/RailwaySystem/Views/PassengerDetails/CancelTickets.cshtml
@model IEnumerable<RailwaySystem.Models.PassengerDetails>

@{
    ViewData["Title"] = "ListPassengerDetails";
}
<link rel="stylesheet" href="~/css/fontAwesome.css">
<link rel="stylesheet" href="~/css/TableCancel.css" />
<h3 class="alert-success">List Passenger Details</h3>
<br />
<p>
    <a href="@Url.Action("Index", "Home")">
        <span class="btn btn-outline-success">Home</span>
    </a>
</p>
<p>
    <a style="color:blue;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">Passengers pay the ticket 4 hours before the train departure time.</a>
</p>
<hr />
<div>
    <form asp-action="CancelTickets" asp-controller="PassengerDetails">
        <label>Search by Ticket ID/Train ID&nbsp;&nbsp;</label>
        <div class="input-group col-lg-6 mb-4">

            <input type="text" name="varLocal2" class="form-control bg-white border-left-0 border-md" />
            <input type="text" name="varLocal" hidden value="@ViewBag.userid" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" value="Search" class="btn btn-outline-info" />
        </div>
        
        
    </form>
</div>
<hr />
<h5 class="alert-info">&nbsp;&nbsp;The train is about to depart</h5>
<!--bang moi-->
<div class="container">
    <ul class="responsive-table">
        <li class="table-header">
            <div class="col col-1">@Html.DisplayNameFor(model => model.UserID)</div>
            <div class="col col-2">@Html.DisplayNameFor(model => model.Name)</div>
            <div class="col col-3">@Html.DisplayNameFor(model => model.Source)</div>
            <div class="col col-4">@Html.DisplayNameFor(model => model.Destination)</div>
            <div class="col col-5">@Html.DisplayNameFor(model => model.Departure)</div>
            <div class="col col-6">@Html.DisplayNameFor(model => model.TrainNo)</div>
            <div class="col col-7">CAR</div>
            <div class="col col-8">@Html.DisplayNameFor(model => model.SeatCode)</div>
            <div class="col col-9">@Html.DisplayNameFor(model => model.Price)</div>
            <div class="col col-10"></div>

        </li>
        @foreach (var item in Model)
        {
            if ((item.Departure - DateTime.Now).TotalMinutes > 0)
            {
                <li class="table-row">
                    <div class="col col-1">@Html.DisplayFor(modelItem => item.UserID)</div>
                    <div class="col col-2">@Html.DisplayFor(modelItem => item.Name)</div>
                    <div class="col col-3">@Html.DisplayFor(modelItem => item.Source)</div>
                    <div class="col col-4">@Html.DisplayFor(modelItem => item.Destination)</div>
                    <div class="col col-5">@Html.DisplayFor(modelItem => item.Departure)</div>
                    <div class="col col-6">@Html.DisplayFor(modelItem => item.TrainNo)</div>
                    <div class="col col-7">@Html.DisplayFor(modelItem => item.Compartment)</div>
                    <div class="col col-8">@Html.DisplayFor(modelItem => item.SeatCode)</div>
                    <div class="col col-9">@Html.DisplayFor(modelItem => item.Price)</div>
                    <div class="col col-10">
                        @Html.ActionLink("Delete", "DeleteTickets", new { varLocal = item.PNR }, new { @class = "btn btn-outline-danger btn-md" })

                    </div>

                </li>
            }
        }

    </ul>
</div>
<hr />
<h5 class="alert-info">&nbsp;&nbsp;The train has departed</h5>
<div class="container">
    <ul class="responsive-table">
        <li class="table-header">
            <div class="col col-1">@Html.DisplayNameFor(model => model.UserID)</div>
            <div class="col col-2">@Html.DisplayNameFor(model => model.Name)</div>
            <div class="col col-3">@Html.DisplayNameFor(model => model.Source)</div>
            <div class="col col-4">@Html.DisplayNameFor(model => model.Destination)</div>
            <div class="col col-5">@Html.DisplayNameFor(model => model.Departure)</div>
            <div class="col col-6">@Html.DisplayNameFor(model => model.TrainNo)</div>
            <div class="col col-7">CAR</div>
            <div class="col col-8">@Html.DisplayNameFor(model => model.SeatCode)</div>
            <div class="col col-9">@Html.DisplayNameFor(model => model.Price)</div>
            <div class="col col-10"></div>

        </li>
        @foreach (var item in Model)
        {
            if ((item.Departure - DateTime.Now).TotalMinutes <= 0)
            {
                <li class="table-row">
                    <div class="col col-1">@Html.DisplayFor(modelItem => item.UserID)</div>
                    <div class="col col-2">@Html.DisplayFor(modelItem => item.Name)</div>
                    <div class="col col-3">@Html.DisplayFor(modelItem => item.Source)</div>
                    <div class="col col-4">@Html.DisplayFor(modelItem => item.Destination)</div>
                    <div class="col col-5">@Html.DisplayFor(modelItem => item.Departure)</div>
                    <div class="col col-6">@Html.DisplayFor(modelItem => item.TrainNo)</div>
                    <div class="col col-7">@Html.DisplayFor(modelItem => item.Compartment)</div>
                    <div class="col col-8">@Html.DisplayFor(modelItem => item.SeatCode)</div>
                    <div class="col col-9">@Html.DisplayFor(modelItem => item.Price)</div>
                    <div class="col col-10">
                        <i class="fa fa-times fa-3x" aria-hidden="true"></i>

                    </div>

                </li>
            }
        }

    </ul>
</div>

RailwaySystem/RailwaySystem/Views/PassengerDetails/Delete.cshtml
@model RailwaySystem.Models.PassengerDetails

@{
    ViewData["Title"] = "Delete";
}

<h3 class="alert-success">Delete</h3>
<br />
<h4>Are you sure you want to delete this?</h4>
<div>
    <h4>PassengerDetails</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
    </dl>

    <form asp-action="Delete" enctype="multipart/form-data" method="post">
        <input type="hidden" asp-for="PNR" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" onclick="return confirm('Are you sure you want to delete?')" />
        <a href="@Url.Action("ListPassengerDetails", "PassengerDetails")">
            <span class="btn btn-outline-primary">Back</span>
        </a>
    </form>
</div>

RailwaySystem/RailwaySystem/Views/PassengerDetails/FindTrainList.cshtml
@model IEnumerable<RailwaySystem.Models.TrainDetails>

@{
    ViewData["Title"] = "FindTrainDetails";
}

<link rel="stylesheet" href="~/css/TableIndex.css">

<h4 class="alert-info"><a style="color:darkblue">&nbsp;&nbsp;&equiv;&nbsp;Search results for a list of trains</a></h4>
<hr />
<a href="@Url.Action("Index", "Home")">
    <span class="btn btn-outline-primary">Back</span>
</a>
 &nbsp;&nbsp;<a style="color:blue;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">Passengers pay the ticket 4 hours before the train departure time.</a>
<hr />

@if (ViewBag.ticketbuy != null)
{
    <a style="color:red;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">&nbsp;&nbsp;You have paid for @ViewBag.ticketbuy tickets. Check the train ticket to see if there is a duplicate ticket. If you have not printed tickets, select the menu Print ticket</a>
}

<h5 style="color:red">@ViewBag.msg</h5>

<div class="container">
    <form asp-action="FindTrainList" asp-controller="PassengerDetails" enctype="multipart/form-data" method="post">
        <table align="left">
            <tr>
                <td align="center">From</td>
                <td></td>
                <td align="center">To</td>
                <td></td>
                <td align="center">Date</td>
                <td></td>
            </tr>
            <tr>
                <td>
                    

                    <div class="input-group col-lg-12 mb-4">
                        
                        <select name="varLocal" asp-items="ViewBag.arr" class="form-control custom-select bg-white border-left-0 border-md">
                            <option>Choose your start point...</option>
                        </select>
                    </div>
                </td>
                <td>
                    <img src="~/images/selectbox2.png" alt="change" width="30" height="30" />&nbsp;&nbsp;&nbsp;
                </td>
                
                <td>
                    

                    <div class="input-group col-lg-12 mb-4">
                        
                        <select name="varLocal2" asp-items="ViewBag.dep" class="form-control custom-select bg-white border-left-0 border-md">
                            <option>Choose your end point...</option>
                        </select>
                    </div>
                </td>
                <td>
                    <img src="~/images/selectbox2.png" alt="change" width="30" height="30" />&nbsp;&nbsp;&nbsp;
                </td>
                <td>
                    <div class="input-group col-lg-12 mb-4">
                        

                        <input placeholder="Date of Birth" id="Text1" name="departure" type="date" class="form-control bg-white border-left-0 border-md" />

                    </div>
                </td>
                <td>
                    <input type="submit" value="Search" class="btn btn-outline-danger" />
                </td>
            </tr>
            <tr><td>&nbsp;</td></tr>
        </table>

    </form>

</div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <ul class="responsive-table">
        <li class="table-header">
            <div class="col col-1">@Html.DisplayNameFor(model => model.TrainNo)</div>
            <div class="col col-2">@Html.DisplayNameFor(model => model.TrainName)</div>
            <div class="col col-3">@Html.DisplayNameFor(model => model.Source)</div>
            <div class="col col-4">@Html.DisplayNameFor(model => model.Destination)</div>
            <div class="col col-5">@Html.DisplayNameFor(model => model.Departure)</div>
            <div class="col col-6"></div>
        </li>
        @foreach (var item in Model)
        {
            <li class="table-row">
                <div class="col col-1">@item.TrainNo</div>
                <div class="col col-2">@item.TrainName</div>
                <div class="col col-3">@item.Source</div>
                <div class="col col-4">@item.Destination</div>
                <div class="col col-5">@item.Departure.ToShortDateString()</div>
                <div class="col col-6">
                    @Html.ActionLink("ViewDetails", "Details", "TrainDetails", new { varLocal = item.TrainNo }, new { @class = "btn btn-outline-primary btn-md" })

                    @*<a href="@Url.Action("Details", "TrainDetails", new {varLocal = item.TrainNo })">
                            <span class="btn btn-primary btn-outline-primary btn-md">ViewDetails</span>
                        </a>*@
                    @if (ViewBag.username != null && item.Status == true && (item.Departure - DateTime.Now).TotalHours >= 4)
                    {
                        @Html.ActionLink("Book a seat", "FindSeat", "PassengerDetails", new { varLocal = item.TrainNo, varLocal2 = 1 }, new { @class = "btn btn-outline-success btn-md" }) @*<a href="@Url.Action("FindSeat", "PassengerDetails", new {varlocal=item.TrainNo,varLocal2 = 1})">
                                <span class="btn btn-success btn-outline-success btn-md">Book a seat</span>
                            </a>*@}
                </div>
            </li>
        }
    </ul>
</div>

RailwaySystem/RailwaySystem/Views/PassengerDetails/PrintQRCode.cshtml
@model RailwaySystem.Models.PassengerDetails
@addTagHelper *, Microsoft.AspNetCore.Razor.TagHelpers
@addTagHelper *, RailwaySystem

@{
    ViewData["Title"] = "PrintQRCode";
}

<h3 class="alert-success">Details Ticket</h3>
<br />
<p>
    <a href="@Url.Action("Index", "Home")">
        <span class="btn btn-outline-primary">Home</span>
    </a>
    <a href="@Url.Action("PrintTickets", "PassengerDetails",new {varLocal=ViewBag.userid})">
        <span class="btn btn-outline-success">Back</span>
    </a>
</p>

<h5 style="color:red">Ticket information</h5>
<hr />
<table width="100%" cellpadding="6">
    <tr>
        <td width="20%">First and last name:</td>
        <td width="30">@Model.Name</td>
        <td width="50%" rowspan="9">
            <qrcode content="@ViewBag.stringcode" width="200" height="200"></qrcode>
        </td>
    </tr>
    <tr>
        <td>Gender:</td>
        <td>@ViewBag.gender</td>
    </tr>
    <tr>
        <td>Phone:</td>
        <td>@Model.PhoneNo</td>
    </tr>
    <tr>
        <td>Address Email:</td>
        <td>@Model.Email</td>
    </tr>
    <tr>
        <td>Train:</td>
        <td>@ViewBag.trainname</td>
    </tr>
    <tr>
        <td>Station go:</td>
        <td>@Model.Source</td>
    </tr>
    <tr>
        <td>Arrivals:</td>
        <td>@Model.Destination</td>
    </tr>
    <tr>
        <td>Departure:</td>
        <td>@Model.Departure</td>
    </tr>
    <tr>
        <td>Compartment:</td>
        <td>@Model.Compartment</td>
    </tr>
    <tr>
        <td>Seat Code:</td>
        <td>@Model.SeatCode</td>
    </tr>
    <tr>
        <td>Price:</td>
        <td>@Model.Price</td>
        <td>
            <a href="@Url.Action("ExportToPdf", "PassengerDetails",new {varLocal=Model.PNR})">
                <span class="btn btn-outline-warning">Export to Pdf</span>
            </a>
        </td>
    </tr>
</table>